# Configuration for Cite-and-Challenge Peer Protocol System

# Database Configuration
database:
  type: "sqlite"
  path: "data/system.db"

# API Keys Configuration
api_keys:
  openai_key: ""
  anthropic_key: ""
  google_search_key: ""
  bing_search_key: ""

# Search Configuration
search:
  providers: ["duckduckgo"]
  rate_limits:
    duckduckgo: 60
    google: 100
    bing: 100
  timeout: 30
  max_results: 10

# Agent Configuration
agents:
  max_tokens: 4000
  temperature: 0.1
  model: "gpt-4"
  backup_model: "claude-3-sonnet-20241022"

# System Configuration
system:
  log_level: "INFO"
  log_file: "logs/system.log"
  max_claim_length: 500
  max_citation_count: 20
  revision_rounds: 1

# Domain Configuration
domains:
  - name: "health"
    keywords: ["health", "medical", "disease", "exercise", "diet", "medicine"]
    complexity_weight: 0.8
  - name: "environment"
    keywords: ["climate", "environment", "energy", "carbon", "sustainable"]
    complexity_weight: 0.9
  - name: "technology"
    keywords: ["technology", "ai", "digital", "remote", "software"]
    complexity_weight: 0.7
  - name: "general"
    keywords: ["general", "other", "misc"]
    complexity_weight: 0.5

# Evaluation Configuration
evaluation:
  hallucination_threshold: 0.85
  citation_precision_target: 0.85
  citation_recall_target: 0.90
  statistical_significance: 0.05