database:
  type: "sqlite"
  path: "data/claims.db"
  postgresql:
    host: "localhost"
    port: 5432
    database: "cite_challenge"
    username: ""
    password: ""

api_keys:
  openai_key: ""
  anthropic_key: ""
  google_search_key: ""
  bing_search_key: ""

search:
  providers:
    - "google"
    - "bing" 
    - "duckduckgo"
  rate_limits:
    google: 100
    bing: 100
    duckduckgo: 50
  timeout: 30
  max_results: 10

agents:
  max_tokens: 4000
  temperature: 0.1
  model: "gpt-4"
  backup_model: "claude-3-sonnet-20241022"

system:
  log_level: "INFO"
  log_file: "logs/system.log"
  max_claim_length: 500
  max_citation_count: 20
  revision_rounds: 1

domains:
  - name: "science"
    keywords: ["research", "study", "experiment", "theory", "hypothesis"]
    complexity_weight: 1.2
  - name: "health"
    keywords: ["medical", "health", "disease", "treatment", "symptoms"]
    complexity_weight: 1.1
  - name: "history"
    keywords: ["historical", "past", "century", "ancient", "civilization"]
    complexity_weight: 1.0
  - name: "finance"
    keywords: ["economic", "financial", "market", "investment", "monetary"]
    complexity_weight: 1.3

evaluation:
  hallucination_threshold: 0.85
  citation_precision_target: 0.85
  citation_recall_target: 0.90
  statistical_significance: 0.05